// <auto-generated />
namespace LojaVeiculos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class veiculos_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(veiculos_update));
        
        string IMigrationMetadata.Id
        {
            get { return "201710172136342_veiculos_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
